debug = true

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[api]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "analysis.keithhanson.io"
watch = true
exposedByDefault = false

[acme]
email = "keith@keithhanson.io"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.dnsChallenge]
provider = "dnsimple" # DNS Provider name (cloudflare, OVH, gandi...)
delayBeforeCheck = 0
[[acme.domains]]
main = "analysis.keithhanson.io"
