version: '2'

services:
  traefik:
    image: traefik:v1.7
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/traefik/traefik.toml:/traefik.toml
      - ./conf/traefik/acme.json:/acme.json
    container_name: traefik
    environment:
      - DNSIMPLE_OAUTH_TOKEN=${DNSIMPLE_OAUTH_TOKEN}
      - DNSIMPLE_BASE_URL=https://api.dnsimple.com/

networks:
  web:
    external: true
