default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['RAILS_DB_HOST'] %>
  database: upload_to_futter
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
